-- AlterTable
ALTER TABLE `dispositivos` ADD COLUMN `creadoEn` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `usuario_dispositivos` ADD COLUMN `icono` VARCHAR(191) NULL,
    ADD COLUMN `nombrePersonalizado` VARCHAR(191) NULL,
    ADD COLUMN `tipoObjeto` ENUM('TV', 'REFRIGERADOR', 'LAVADORA', 'MICROONDAS', 'AIRE_ACONDICIONADO', 'VENTILADOR', 'COMPUTADORA', 'LAPTOP', 'CONSOLA_VIDEOJUEGOS', 'ILUMINACION', 'ROUTER', 'CARGADOR', 'CAFETERA', 'LICUADORA', 'HORNO', 'PLANCHA', 'SECADORA', 'CALENTADOR', 'BOMBA_AGUA', 'OTRO') NULL,
    ADD COLUMN `ubicacion` VARCHAR(191) NULL;
